### ISSUE TITLE
deps: upstream project dependencies are outdated

### ISSUE THREAD

**Issue by DerekNonGeneric** [openinf/nodejs-github-bot#13]
As seen in this repo's open pull requests tab, the upstream version of this project has not been keeping its dependencies up-to-date. I discovered it by accident but would like to bring this to the attention of the folks who maintain this project in the [@nodejs](https://github.com/nodejs/) org in hopes that they can get it taken care of over there.

/cc @Trott @phillipj

**Comment by Trott** [comment]
Thanks. I'll enable dependabot on that repo so we stay closer to up-to-date.

**Comment by DerekNonGeneric** [comment]
Thanks, @Trott; going to delete this now and make a new fork once that `@octokit/rest` dep gets bumped (if you're able).
